In [ ]:
#Ckreating a range of elements from 1 to 30
import numpy
arr = numpy.array(range(1,30))
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [ ]:
#to give multiple values in array like rows and colunms we can give eye instead of identity
#eye() --> used to define both user defined rows and columns
#identity--> is used to define some number of rows and columns
#syntax: np.identity(4)--> means 4 rows and 4 columns
#syntax: np. eye(rows,columns)
arr = numpy.eye(5,5)
arr

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
#to print the identity matrxi in a complex numbers format
numpy.identity(5,dtype=complex)

array([[1.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 1.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 1.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 1.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 1.+0.j]])

In [ ]:
#To perform multidimentional slicing
#syntax:--> numpy.arange(values).reshape(range)
arr = numpy.arange(25).reshape(5,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
#proper key to find the m x n matrix size
#syntax:-->arrayname.shape
arr.shape

(5, 5)

In [ ]:
#arr[rows,columns,step]
#arr[row_start,rows_end;column_start,column_end,step]
arr [0:3]

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
#arr[row_start,rows_end;column_start,column_end,step]
arr[1:3,1:4]

array([[ 6,  7,  8],
       [11, 12, 13]])

In [ ]:
#negative index slicing
arr[1:-2]


array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
arr[0:3,1:-1]

array([[ 1,  2,  3],
       [ 6,  7,  8],
       [11, 12, 13]])

In [ ]:
arr[-4:-2]

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
arr[-4:-2,-4:-2]

array([[ 6,  7],
       [11, 12]])

In [ ]:
##inbulit functions##
#sum--> numpy.sum(arayname,axis=0) --> adds the elements based on column wise axis=0
arr = numpy.arange(25).reshape(5,5)
arr1 = numpy.sum(arr,axis=0)
arr1


array([50, 55, 60, 65, 70])

In [ ]:
##inbuilt functions##

#mean --> centre value
#median --> max number of repeated element
#variance --> median/total no.of elemnts
#standard deviation --> sqrt of variance

In [ ]:
## linspace--> used to get the evenly separated points between the given range of values
#syntax:--> numpy.linspace(range) or //numpy.linspace(start,end,difference by how much it want (ex:5)
numpy.linspace(1,10)


array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [ ]:
# if we wnat to know the difference value by using which the values are segregated
#syntax:--> retstep=True
numpy.linspace(12,30,12,retstep=True)

(array([12.        , 13.63636364, 15.27272727, 16.90909091, 18.54545455,
        20.18181818, 21.81818182, 23.45454545, 25.09090909, 26.72727273,
        28.36363636, 30.        ]),
 1.6363636363636365)

In [ ]:
#to pick the random element between the range
#syntax: --> numpy.random.randint(start,end)
#or // numpy.random.randint(40)
#or// numpy.random.randint(1,2,3-->no of values)
numpy.random.randint(10,30,8)

array([11, 14, 13, 18, 21, 11, 24, 26])

In [ ]:
#rand()-->
#to get the randomly, generated values from 0 to 1, based on
#uniform distribution
#syntax: --> numpy.random.rand(value)
numpy.random.rand(10)

array([0.84551896, 0.0061505 , 0.72871666, 0.44550154, 0.94141583,
       0.03023867, 0.64884802, 0.51233845, 0.03624161, 0.89847663])

In [ ]:
#rand()-->
#to get the randomly genearted values from 0 to 1
#based on normal distribution
#syntax:--> numpy.random.randn(value)
numpy.random.randn(5,4)

array([[ 1.45231374, -0.32533899, -0.04810814,  0.67119229],
       [-0.07173154,  0.00300008,  0.1282321 , -0.23133288],
       [-0.37873414, -0.01995905,  0.48239003,  1.7002976 ],
       [ 1.13031796, -0.4953664 ,  0.75637062,  0.79764278],
       [ 1.48546472,  1.01038738, -0.82302204,  1.23790357]])

In [ ]:
#to fine the minimum and maximum indices
#minimum index syntax:--> arrayname.argmin()
#maximum index value syntax:--> arrayname.argmax()

arr = [1,2,31,4,0]
arr = numpy.array(arr)
print(arr.argmin()) #prints the index value of least element
print(arr.argmax()) #prints the index value of highest element

4
2


In [ ]:
#to print the values of cos ,sin ,and tan based on array values
#syntax:-->numpy.sin(arrayname)//numpy.cos(arrayname)
#we can also print cosec cot and secant values
a = numpy.sin(arr)
print(a)
b = numpy.cos(arr)
print(b)
c = numpy.tan(arr)
print(c)

[ 0.84147098  0.90929743 -0.40403765 -0.7568025   0.        ]
[ 0.54030231 -0.41614684  0.91474236 -0.65364362  1.        ]
[ 1.55740772 -2.18503986 -0.44169557  1.15782128  0.        ]


In [ ]:
arr1 = numpy.array([1,2,3,4,7,9,10])
arr2 = numpy.array([5,6,7,8])
a = numpy.array([len(arr1)-len(arr2)])
print(a)
if len(arr1)==len(arr2):
  s= numpy.multiply(arr1,arr2)
  print(s)
  print(sum(s))
else:
  arr2 = numpy.append([arr2],[1,1,1])

  sum1=numpy.multiply(arr1,arr2)
  print(sum1)
  print(sum(sum1))






[3]
[ 5 12 21 32  7  9 10]
96


In [ ]:
#to print nan values
arr = [1,2,3,4,numpy.nan,numpy.nan]
arr = [~numpy.isnan(arr)] # [numpy.isnan(arr)] for compplement of arr
print(arr)


[array([ True,  True,  True,  True, False, False])]


In [ ]:
#to find the total sum by multiplying
#1x3 + 2x3 + 3x4 + 4x5 = 40
import numpy
n1 = [1,2,3,4]
n2 = [2,3,4,5]
numpy.dot(n1,n2)

40

In [ ]:
##pandas##
#pandas is defined as an open-source library that provoides
#hugh performance data manupulating in python
#data analysis requires lot of pricesiiong such as restructureing, cleaning, merging, manipulating etc,,
#we prefer pandas to perform the above funtionalities bcoz it is fast, simple than other tools
#pandas is built on numpy, numpy is required for opening pandas


In [ ]:
#pandas series
#pandas seris is a data structure with one dimension labelled array
#it is a primary building block of dataframe,making its rows and columns


In [ ]:
labels = ['a','b','c']
my_data = [10,20,30]
arr = numpy.array(my_data)
d = {"a":100,"b":200,"c":300}
print(d)

{'a': 100, 'b': 200, 'c': 300}


In [ ]:
#syntax:--> pandas.Series()data=None,index= NOne,dtype=None,name=Name,copy=None
#example: 1
import pandas as pd
#pd.Series(data=my_data,index=labels)// or
pd.Series(my_data,labels)

In [ ]:
#to print the Series of data
pd.Series(my_data)

0    10
1    20
2    30
dtype: int64

In [ ]:
#series of elements
se1 = pd.Series([1,2,3,4,5],["USA","INDIA","CANADA","UK","PARIS"])
se1

USA       1
INDIA     2
CANADA    3
UK        4
PARIS     5
dtype: int64

In [ ]:
#printing the series values directly
#syntax:--> seriesname["valuename"]
se1['USA']

1

In [ ]:
#slicing the series
#syntx:-->seriesname[start:end]
se1[2:5]

CANADA    3
UK        4
PARIS     5
dtype: int64

In [ ]:
#we can concatenate the series
#syntax:-->series1+series2
se2=pd.Series([12,18,17],["HARIKA","MANU","HELLO"])
se1+se2

CANADA   NaN
HARIKA   NaN
HELLO    NaN
INDIA    NaN
MANU     NaN
PARIS    NaN
UK       NaN
USA      NaN
dtype: float64

In [ ]:
#we can add to element to an existing series
#syntax:-->series_name["element value"]="key value"
se2["china"]="duplicate"
se2

HARIKA           12
MANU             18
HELLO            17
china     duplicate
dtype: object

In [ ]:
#Data frames
#syntax:--> pd.DataFrame(data,row_label,column_label)
df = pd.DataFrame(numpy.random.randn(5,4))
df

0         1         2         3
0 -1.634578 -0.986174  0.129449 -0.572030
1 -0.554934 -0.882004  0.486925  2.018468
2  0.246417 -0.268149 -0.686365  1.339640
3  1.117776 -0.204536 -0.416350 -0.148943
4  0.196862 -0.110798 -0.636185 -2.080442

from matplotlib import pyplot as plt
df[0].plot(kind='hist', bins=20, title=0)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
df[1].plot(kind='hist', bins=20, title=1)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
df[2].plot(kind='hist', bins=20, title=2)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
df[3].plot(kind='hist', bins=20, title=3)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
df.plot(kind='scatter', x=0, y=1, s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
df.plot(kind='scatter', x=1, y=2, s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
df.plot(kind='scatter', x=2, y=3, s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  from matplotlib import pyplot as plt
  import seaborn as sns
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series[1]
  ys = series[0]
  
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = df.sort_values(1, ascending=True)
_plot_series(df_sorted, '')
sns.despine(fig=fig, ax=ax)
plt.xlabel(1)
_ = plt.ylabel(0)

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  from matplotlib import pyplot as plt
  import seaborn as sns
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series[1]
  ys = series[2]
  
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = df.sort_values(1, ascending=True)
_plot_series(df_sorted, '')
sns.despine(fig=fig, ax=ax)
plt.xlabel(1)
_ = plt.ylabel(2)

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  from matplotlib import pyplot as plt
  import seaborn as sns
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series[1]
  ys = series[3]
  
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = df.sort_values(1, ascending=True)
_plot_series(df_sorted, '')
sns.despine(fig=fig, ax=ax)
plt.xlabel(1)
_ = plt.ylabel(3)

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  from matplotlib import pyplot as plt
  import seaborn as sns
  palette = list(sns.palettes.mpl_palette('Dark2'))
  counted = (series[1]
                .value_counts()
              .reset_index(name='counts')
              .rename({'index': 1}, axis=1)
              .sort_values(1, ascending=True))
  xs = counted[1]
  ys = counted['counts']
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = df.sort_values(1, ascending=True)
_plot_series(df_sorted, '')
sns.despine(fig=fig, ax=ax)
plt.xlabel(1)
_ = plt.ylabel('count()')

from matplotlib import pyplot as plt
df[0].plot(kind='line', figsize=(8, 4), title=0)
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
df[1].plot(kind='line', figsize=(8, 4), title=1)
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
df[2].plot(kind='line', figsize=(8, 4), title=2)
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
df[3].plot(kind='line', figsize=(8, 4), title=3)
plt.gca().spines[['top', 'right']].set_visible(False)

In [ ]:
#we can insert values also like row and column values to represent as arguments
#syntax:--> pd.DataFrame(numpy.randim.randn(range),[rows keys],[column keys])
df = df = pd.DataFrame(numpy.random.randn(5,4),['A','B','C','D','E'],['w','x','y','z'])
df

w         x         y         z
A  0.156342  0.983837 -0.424323 -1.624334
B  0.016227 -0.995656  0.284020  1.419825
C  0.238647 -0.585673  1.538780  0.954331
D  0.306530  0.397635  1.031919  0.980493
E -0.815882 -0.571805  0.156691  0.924892

In [ ]:
#how to convert ditctionary into dataframe
d = {"col1":[1,2],"col2":[3,4],"col3":[5,6],"col4":['a','b']}
df = pd.DataFrame(data = d)
df

col1  col2  col3 col4
0     1     3     5    a
1     2     4     6    b

In [ ]:
#to transpose the data
df.T

A         B         C         D         E
w  0.156342  0.016227  0.238647  0.306530 -0.815882
x  0.983837 -0.995656 -0.585673  0.397635 -0.571805
y -0.424323  0.284020  1.538780  1.031919  0.156691
z -1.624334  1.419825  0.954331  0.980493  0.924892

In [ ]:
#TO GET ALL THE ROW NOMES
df.index

Index(['A', 'B', 'C', 'D', 'E'], dtype='object')

In [ ]:
#to get the all column names
print(df.columns)
type(df)

Index(['w', 'x', 'y', 'z'], dtype='object')


pandas.core.frame.DataFrame

In [ ]:
#to get the values in a database
df.values

array([[ 0.1563415 ,  0.98383693, -0.42432346, -1.62433423],
       [ 0.01622738, -0.99565616,  0.28401961,  1.41982501],
       [ 0.23864669, -0.58567289,  1.53878038,  0.9543314 ],
       [ 0.30652977,  0.39763487,  1.0319193 ,  0.98049302],
       [-0.81588157, -0.57180545,  0.15669059,  0.92489186]])

In [ ]:
#to find the datatype of the rows
df.dtypes

w    float64
x    float64
y    float64
z    float64
dtype: object

In [ ]:
#to find the horizontal and vertical (rows and columns) indices
df.axes

[Index(['A', 'B', 'C', 'D', 'E'], dtype='object'),
 Index(['w', 'x', 'y', 'z'], dtype='object')]

In [ ]:
#to find the dimension of the database
df.ndim

2

In [ ]:
#to find the size of the database
df.size

20

In [ ]:
type(df['w'])

pandas.core.series.Series

In [ ]:
#to get the specified columns
df[['w','x','y']]

w         x         y
A  0.156342  0.983837 -0.424323
B  0.016227 -0.995656  0.284020
C  0.238647 -0.585673  1.538780
D  0.306530  0.397635  1.031919
E -0.815882 -0.571805  0.156691

In [ ]:
#with the existing column creating new column

#syntx:--> df_name['newcolumn_name'] = df_name['existing_1'] + ['existing_2']

df['new'] = df['w']+df['y']
df


w         x         y         z       new
A  0.156342  0.983837 -0.424323 -1.624334 -0.267982
B  0.016227 -0.995656  0.284020  1.419825  0.300247
C  0.238647 -0.585673  1.538780  0.954331  1.777427
D  0.306530  0.397635  1.031919  0.980493  1.338449
E -0.815882 -0.571805  0.156691  0.924892 -0.659191

In [ ]:
#to delete the column from the database

#syntax: --> df_name.drop('new',axis=1)

df.drop('new',axis=1)

w         x         y         z
A  0.156342  0.983837 -0.424323 -1.624334
B  0.016227 -0.995656  0.284020  1.419825
C  0.238647 -0.585673  1.538780  0.954331
D  0.306530  0.397635  1.031919  0.980493
E -0.815882 -0.571805  0.156691  0.924892

In [ ]:
df

w         x         y         z       new
A  0.156342  0.983837 -0.424323 -1.624334 -0.267982
B  0.016227 -0.995656  0.284020  1.419825  0.300247
C  0.238647 -0.585673  1.538780  0.954331  1.777427
D  0.306530  0.397635  1.031919  0.980493  1.338449
E -0.815882 -0.571805  0.156691  0.924892 -0.659191

In [ ]:
#to delete the column permenantly from the database

#syntax:--> dataframe_name.drop('column_name',axis = 1,inplace = True)

df.drop('new',axis=1,inplace= True)
df

w         x         y         z
A  0.156342  0.983837 -0.424323 -1.624334
B  0.016227 -0.995656  0.284020  1.419825
C  0.238647 -0.585673  1.538780  0.954331
D  0.306530  0.397635  1.031919  0.980493
E -0.815882 -0.571805  0.156691  0.924892

In [ ]:
##HOME WORK##



#add another row to the array [[1,2,3],[45,4,7],[9,6,10]] and the row to be added is[12,23,45]
import numpy
arr = numpy.array([[1,2,3],[45,4,7],[9,6,10]])
arr1 = ([12,23,45])
add = numpy.append([arr],[arr1])
add.reshape(4,3)


array([[ 1,  2,  3],
       [45,  4,  7],
       [ 9,  6, 10],
       [12, 23, 45]])

In [ ]:
#to find the freaquency of elements in series
#syntax:--> series_name.value_counts().to_dict()// .to_list() or// to_tuple()
import pandas as pd
se1 = pd.Series([1,1,1,2,2,2,23,3,3,4,4,5])
freq = se1.value_counts().to_dict()
print(freq)

{1: 3, 2: 3, 3: 2, 4: 2, 23: 1, 5: 1}


In [ ]:
#
ser = pd.Series(numpy.random.randint(1,10,35))
print(ser)
df = pd.DataFrame(ser.values.reshape(5,7))
df

0     4
1     6
2     7
3     9
4     3
5     4
6     2
7     1
8     3
9     2
10    4
11    5
12    8
13    2
14    4
15    6
16    7
17    3
18    4
19    7
20    2
21    9
22    4
23    8
24    7
25    7
26    3
27    1
28    8
29    4
30    7
31    9
32    8
33    5
34    1
dtype: int64


0  1  2  3  4  5  6
0  4  6  7  9  3  4  2
1  1  3  2  4  5  8  2
2  4  6  7  3  4  7  2
3  9  4  8  7  7  3  1
4  8  4  7  9  8  5  1

In [ ]:
#reshapethe series ser into a dataframe
ser = pd.Series(numpy.random.randint(1,10,10))
#syntax is given as below
pos = ser[ser % 3 == 0].index.tolist()
pos

[0, 4, 5, 6, 8]

In [ ]:
#join the teo series given below
ser1 = pd.Series(range(5))
ser2 = pd.Series(list('abcde'))
#syntax is written as below
ser3 = pd.concat([ser1,ser2])
ser3

0    0
1    1
2    2
3    3
4    4
0    a
1    b
2    c
3    d
4    e
dtype: object

In [ ]:
#write a pandas program to select the'name' and 'score' columns from the following DataFrame
#sample python dictionary data and list labels are given below
exam_data = {'name':['Anastasia','Dima','Katherine','James','Emily','Michael','Matthew','laura','Kevin','Jonas'],'Score':[12.5,9,16.5,numpy.nan,9,20,14.5,numpy.nan,8,19],'attempts':[1,3,2,3,2,3,1,1,2,1],'qualify':['yes','no','yes','no','no','yes','yes','no','no','yes']}
labels = ['a','b','c','d','e','f','g','h','i','j']
df = pd.DataFrame(exam_data, index = labels)
selected_columns = df[['name','Score']]
selected_columns

name  Score
a  Anastasia   12.5
b       Dima    9.0
c  Katherine   16.5
d      James    NaN
e      Emily    9.0
f    Michael   20.0
g    Matthew   14.5
h      laura    NaN
i      Kevin    8.0
j      Jonas   19.0