In [ ]:
import numpy
l1 = [1,2,3,4,5]
arr = numpy.array(l1)
print(arr)

[1 2 3 4 5]


In [ ]:
import numpy
l2 = (1,2,3,4,5)
arr = numpy.array(l1)
print(arr)
arr1 = tuple(arr)
print(arr1)
arr.dtype

[1 2 3 4 5]
(1, 2, 3, 4, 5)


dtype('int64')

In [ ]:
import numpy
l2 = {1,2,3,4,5}
arr = numpy.array(l2)
print(arr)

{1, 2, 3, 4, 5}


In [ ]:
import numpy
l3 = ("harika","hello","bye")
arr = numpy.array(l3)
print(arr)
arr.tolist()

['harika' 'hello' 'bye']


['harika', 'hello', 'bye']

In [ ]:
class c1:
  name = "hari"
  age = 12

obj = c1()
print(obj.name)
print(obj.age)


hari
12


In [ ]:
import numpy
dic = {1:"hari",2:"bye"}
arr = numpy.array(dic)
print(arr)
arr.tolist()
print(arr)
arr.dtype

{1: 'hari', 2: 'bye'}
{1: 'hari', 2: 'bye'}


dtype('O')

In [ ]:
import numpy
l2 = [1,2,3,4,5]
l1 = list(l2)
print(type(l1))
print(l1)

<class 'list'>
[1, 2, 3, 4, 5]


In [ ]:
import numpy
l2 = [1,2,3,4,5]
l1 = tuple(l2)
print(l1)

(1, 2, 3, 4, 5)


In [ ]:
import numpy
l2 = [1,2,3,4,5]
for i in l2:
  m= i*2
  print(numpy.array(m))

2
4
6
8
10


In [ ]:
import numpy
new = numpy.append(l2,100)
new

array([  1,   2,   3,   4,   5, 100])

In [ ]:
#adding multiple values
#syntax: numpy.append(values also lists and tuples)
new = numpy.append(l2,[11,2,33,44,55])
new


array([ 1,  2,  3,  4,  5, 11,  2, 33, 44, 55])

In [ ]:
#insert()
#syntax:numpy.insert(arrayname,indexposition,value)
l = [1,2,3,4]
new = numpy.insert(l,3,5)
print(new)


[1 2 3 5 4]


In [ ]:
#to insert multiple values inside the array
#syntax:numpy.insert(arrayname,indexposition,values or tuple)
l = [1,2,3,4,11]
new = numpy.insert(l,3,(11,22,33))
print(new)


[ 1  2  3 11 22 33  4 11]


In [ ]:
#to delete element
#syntax:numpy.delete(arrayname,numpy.where(arrayname==value))
l = [1,2,3,4,11]
arr4 = numpy.delete(l,numpy.where(l==11))
arr4

array([ 1,  2,  3,  4, 11])

In [ ]:
#t0 delete number of values in an array
#syntax:numpy.setdiff1d(arrayname,[index values])
new = numpy.setdiff1d(l,[1,3,2])
new

array([ 4, 11])

In [ ]:
#to delete based on index
#synatx:numpy.dlete(index values)
new= numpy.delete(l,4)
new

array([1, 2, 3, 4])

In [ ]:
#to delete multiple values based on index poistion
#syntax: numpy.delete(values)
new = numpy.delete(l,[1,2]) #1,2,3,4,11
new

array([ 1,  4, 11])

In [ ]:
l1 = [1,2,3,4,5,6,7,8,9]
new = numpy.array(l1)
new

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#filter in numpy array into boolean values
#syntax: numpy.array(arrayname)
l1 = [1,2,3,4,5,6,7,8,9]
new = numpy.array(l1)
new
new < 10

array([ True,  True,  True,  True,  True,  True,  True,  True,  True])

In [ ]:
#print the boolean values into list
new = numpy.array(l1)
new[new<30]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
new[(new < 10) & (new>1)]


array([2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#to create id array full of 0's
#syntax: numpy.zeros(no of values)
numpy.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
#to create 2d array full of 0's
numpy.zeros([3,5])


array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
#to craete array full of 1's
numpy.ones(1)

array([1.])

In [ ]:
#to create 2d array full of 1's
numpy.ones([3,4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
#to convert the element in array
#to find the numpy datatype of element present in array
#syntax:ar.type(ar)
new = numpy.ones([2,3],dtype=float)
new



array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:

#we can convert the values in numpy array to various bits
#they are
#int8,int16,int32,int64
new = numpy.zeros([2,4], dtype = 'int16')
new
new = numpy.zeros([2,4], dtype = 'float16')
new


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float16)

In [ ]:
new = numpy.zeros([2,4], dtype = 'complex64')
new

array([[0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j]], dtype=complex64)

In [ ]:
new = numpy.zeros([2,4], dtype = 'complex64')
numpy.int16(new)

<ipython-input-205-5b3e82a6f6a8>:2: ComplexWarning: Casting complex values to real discards the imaginary part
  numpy.int16(new)


array([[0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int16)

In [ ]:
#range of array
#syntax: numpy.array(range())
l1 = numpy.array(range(1,50))
print(l1)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49]


In [ ]:
#to convert a 1d array to multidimentional arrat
new = numpy.ones(1)
new


array([1.])

In [ ]:
new = numpy.ones(1),numpy.ones([2,3,6])
new

(array([1.]),
 array([[[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.]],
 
        [[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.]]]))

In [ ]:
#to convert 1d array to multi
#syntax: --> numpy.reshape(range)
import numpy
l1 = numpy.array(range(1,51))
print(l1)
arr1 = l1.reshape(5,10)
print ('After reshaping having dimension 5*10:')
print (arr1)
print ('\n')

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50]
After reshaping having dimension 5*10:
[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]
 [31 32 33 34 35 36 37 38 39 40]
 [41 42 43 44 45 46 47 48 49 50]]




In [ ]:
#to create an identity matrix
#syntax:--> numpy.identity(upto values)
import numpy
l1 = numpy.array(range(1,51))
print(l1)
arr1 = numpy.identity(50)
print ('identity matrix of 5*10:')
print (arr1)
print ('\n')

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50]
identity matrix of 5*10:
[[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]




In [ ]:
# Slicing with step
 # Skip every other row and column
 #syntax:--> arrayname[range of slicling]
import numpy
l1 = numpy.array(range(1,51))
arr1 = l1.reshape(5,10)
print(arr1)
sliced_matrix = l1[::4]
print(sliced_matrix)

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]
 [31 32 33 34 35 36 37 38 39 40]
 [41 42 43 44 45 46 47 48 49 50]]
[ 1  5  9 13 17 21 25 29 33 37 41 45 49]


In [ ]:
#mean, median, sum, variance, standard deviation
#syntax for mean -->arrayname.mean()
#syntax for median -->numpy.median(arrayname)
#syntax for sum -->arrayname.sum()
#syntax for variance --> numpy.var(arrayname)
#syntax for standard deviation --> numpy.std(arrayname)
print(l1.mean())
print(numpy.median(l1))
print(l1.sum())
print(numpy.var(l1))
print(numpy.std(l1))

25.5
25.5
1275
208.25
14.430869689661812
